### PR TITLE
Allow data URIs to be set as the new tab page

### PR DESCRIPTION
**Pull request by q--**
For example:

    data:text/html,<title>New Tab</title><body style=background:black>

### CODE REVIEW

**Comment by jimschubert** [comment]
Thanks, I'll check this out and merge it if it works for me in Windows and OS X. Sorry about the label... I looked quickly and thought it was a feature request because of your avatar, then I realized it was a PR. :walking:

**Comment by Walkman100** [comment]
If this works, that would be very cool.

**Comment by KIPdeKIP** [comment]
Shouldn't there be a `&&` inbetween the `about:` and `data:` checks?

**Comment by q--** [comment]
@KIPdeKIP You're right. Fixed.

**Comment by jimschubert** [comment]
Looks good, thanks.

**Comment by ibrokemypie** [comment]
This is not working for me with the uri data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/C/HgAGgwJ/lK3Q6wAAAABJRU5ErkJggg==
if you open that itself, you simply see a black screen, but New Tab Redirect breaks on it

**Pull request merged**
